declare module "@editorjs/quote";
declare module "@editorjs/code";
declare module "@editorjs/inline-code";
declare module "@editorjs/checklist";
declare module "@editorjs/raw";
declare module "@editorjs/image";
declare module "@editorjs/simple-image";
declare module "@editorjs/embed";
declare module "@editorjs/marker";
